version: '3'
services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        environment:
            PGDATA: '/var/lib/postgresql/data/pgdata'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'postgres:/var/lib/postgresql/data'
        networks:
            - app
        healthcheck:
            test: 'pg_isready -U postgres -d ${DB_DATABASE}'
            interval: 10s
            timeout: 3s
            retries: 10
    app:
        depends_on:
            db:
                condition: service_healthy
        image: registry.digitalocean.com/thedrawingroom/minova:latest
        build:
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - ./.docker-compose/storage:/app/storage
        ports:
            - "8000:80"
        networks:
            - app
    adminer:
      image: adminer
      restart: always
      ports:
        - "8001:8080"
      networks:
            - app
networks:
    app:
        driver: bridge
volumes:
    postgres:
        driver: local
