tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: no_index_site
            field:
              type: toggle
              display: 'No Index Site'
              localizable: false
