title: 'Product Slider'
fields:
  -
    field:
      type: text
      display: Title
    handle: title
  -
    field:
      type: entries
      display: Products
      collections:
        - products
    handle: products
