title: 'Products Accordion'
fields:
  -
    handle: title
    field:
      type: text
      display: Title
      localizable: true
  -
    handle: sections
    field:
      mode: stacked
      type: grid
      add_row: 'Add Section'
      display: Sections
      localizable: true
      fields:
        -
          field:
            type: text
            display: Label
          handle: label
        -
          field:
            mode: stacked
            type: grid
            fields:
              -
                field:
                  type: text
                  display: Title
                handle: title
              -
                field:
                  type: textarea
                  display: Description
                handle: description
              -
                field:
                  type: entries
                  display: Products
                  collections:
                    - products
                handle: products
            add_row: 'Add Inner Section'
            display: 'Inner Sections'
          handle: inner_sections
