title: 'Product Grid'
fields:
  -
    handle: title
    field:
      type: text
      display: Title
  -
    handle: products
    field:
      collections:
        - products
      type: entries
      display: Products
