title: 'Product Slider'
fields:
  -
    handle: title
    field:
      type: text
      display: Title
      localizable: true
  -
    handle: products
    field:
      type: entries
      display: Products
      collections:
        - products
      localizable: true
