title: 'Product Slider'
fields:
  -
    field:
      type: text
      display: 'Slider Title'
    handle: slider_title
  -
    field:
      type: entries
      display: 'Slider Products'
      collections:
        - products
    handle: slider_products
