tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              display: Title
              validate:
                - required
              localizable: true
          -
            handle: image
            field:
              type: assets
              display: Image
              container: assets
              max_files: 1
              localizable: true
          -
            handle: banner
            field:
              type: group
              display: Banner
              localizable: true
              fields:
                -
                  field:
                    type: text
                    display: Title
                  handle: title
                -
                  field:
                    type: assets
                    display: Image
                    container: assets
                    max_files: 1
                  handle: image
          -
            import: main_bard
          -
            handle: related_products
            field:
              type: entries
              display: 'Related Products'
              collections:
                - products
              localizable: true
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: locale
            field:
              mode: select
              type: terms
              display: Locale
              taxonomies:
                - locale
              localizable: false
          -
            handle: region
            field:
              mode: select
              type: terms
              display: Region
              taxonomies:
                - region
              localizable: false
          -
            handle: indust
            field:
              mode: select
              type: terms
              display: Industries
              taxonomies:
                - indust
              localizable: false
          -
            handle: common_use
            field:
              mode: select
              type: terms
              display: 'Common Use'
              taxonomies:
                - common_use
              localizable: false
          -
            handle: parent
            field:
              type: entries
              collections:
                - products
              max_items: 1
              listable: false
              localizable: true
title: Product
