tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            field:
              type: text
              display: 'Product Title'
              validate:
                - required
            handle: product_title
          -
            config:
              title:
                required: true
            import: hero_banner
          -
            field:
              type: assets
              display: Image
              container: assets
              max_files: 1
            handle: image
          -
            import: main_bard
          -
            field:
              type: entries
              display: 'Related Products'
              collections:
                - products
            handle: related_products
          -
            field:
              type: template
              display: Template
              localizable: true
            handle: template
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            field:
              type: slug
              validate: 'max:200'
              localizable: true
            handle: slug
          -
            field:
              mode: select
              type: terms
              display: Locale
              taxonomies:
                - locale
            handle: locale
          -
            field:
              mode: select
              type: terms
              display: Region
              taxonomies:
                - region
            handle: region
          -
            field:
              mode: select
              type: terms
              display: Industries
              taxonomies:
                - indust
            handle: indust
          -
            field:
              mode: select
              type: terms
              display: 'Common Use'
              taxonomies:
                - common_use
            handle: common_use
          -
            field:
              type: entries
              listable: false
              max_items: 1
              collections:
                - products
              localizable: true
            handle: parent
title: Product
