title: Product
tabs:
  main:
    display: Main
    sections:
      -
        display: 'Product Catagory'
        fields:
          -
            handle: product_name
            field:
              type: text
              validate:
                - required
              display: 'Product Name'
          -
            import: product
            config:
              title:
                required: true
          -
            handle: template
            field:
              type: template
              display: Template
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - products
              max_items: 1
              listable: false
              localizable: true
