title: Product
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              display: Title
          -
            handle: image
            field:
              max_files: 1
              container: assets
              type: assets
              display: Image
          -
            handle: banner
            field:
              type: group
              display: Banner
              fields:
                -
                  handle: title
                  field:
                    type: text
                    display: Title
                -
                  handle: image
                  field:
                    max_files: 1
                    container: assets
                    type: assets
                    display: Image
          -
            import: main_bard
          -
            handle: related_products
            field:
              collections:
                - products
              type: entries
              display: 'Related Products'
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: locale
            field:
              type: terms
              taxonomies:
                - locale
              display: Locale
              mode: select
          -
            handle: region
            field:
              type: terms
              taxonomies:
                - region
              display: Region
              mode: select
          -
            handle: indust
            field:
              type: terms
              taxonomies:
                - indust
              display: Industries
              mode: select
          -
            handle: common_use
            field:
              type: terms
              taxonomies:
                - common_use
              display: 'Common Use'
              mode: select
