tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              display: Title
              validate:
                - required
          -
            handle: image
            field:
              type: assets
              display: Image
              container: assets
              max_files: 1
          -
            handle: short_description
            field:
              character_limit: 150
              type: textarea
              display: 'Short Description'
          -
            handle: banner
            field:
              type: group
              display: Banner
              fields:
                -
                  field:
                    type: text
                    display: Title
                  handle: title
                -
                  field:
                    type: assets
                    display: Image
                    container: assets
                    max_files: 1
                  handle: image
          -
            import: main_bard
          -
            handle: related_products
            field:
              type: entries
              display: 'Related Products'
              collections:
                - products
          -
            handle: downloads
            field:
              type: grid
              display: Downloads
              fields:
                -
                  handle: title
                  field:
                    type: text
                    display: Title
                -
                  handle: file
                  field:
                    max_files: 1
                    container: assets
                    type: assets
                    display: File
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - products
              max_items: 1
              listable: false
              localizable: true
          -
            handle: industry_sectors
            field:
              taxonomies:
                - industries
              type: terms
              display: 'Industry Sectors'
              mode: select
          -
            handle: available_regions
            field:
              taxonomies:
                - region
              type: terms
              display: 'Available Regions'
              mode: select
          -
            handle: common_uses
            field:
              taxonomies:
                - common_use
              type: terms
              display: 'Common Uses'
              mode: select
title: Product
