title: Products
template: products/show
layout: layout
mount: 15db0f71-3808-4546-b86f-a692f83c9a4e
taxonomies:
  - locale
  - region
  - indust
  - common_use
revisions: false
route: '{{ if depth == 1 }}{{ mount }}{{ /if }}{{ parent_uri }}/{{ slug }}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: false
  slugs: true
