stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to Container App
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    variables:
      - group: stg
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: 'ARM_PRD'
        imageToDeploy: '$(containerRegistry)/$(imageRepository):$(tag)'
        containerAppName: '$(containerAppName)'
        resourceGroup: '$(resourceGroupName)'
        containerAppEnvironment: '$(containerAppEnvironment)'
        targetPort: '80'
        environmentVariables: |
          APP_NAME=Minova
          APP_ENV=staging
          APP_KEY=base64:oRRKLNgappG1IiR3N6heuMpTxpKdRs43OpdLFj/s9DM=
          APP_DEBUG=false
          APP_TIMEZONE=Europe/London
          APP_URL=https://staging.minovaglobal.com
          APP_LOCALE=en
          APP_FALLBACK_LOCALE=en
          APP_FAKER_LOCALE=en_GB 
          APP_MAINTENANCE_DRIVER=cache
          APP_MAINTENANCE_STORE=database
          BCRYPT_ROUNDS=12
          LOG_CHANNEL=stack
          LOG_STACK=stderr
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=debug
          DB_CONNECTION=pgsql
          DB_HOST=mi-ne-postgresql.postgres.database.azure.com
          DB_PORT=5432
          DB_DATABASE=corpowebstg
          DB_USERNAME=stgcorpoweb
          DB_PASSWORD=$(db-pass)
          SESSION_DRIVER=database
          SESSION_LIFETIME=120
          SESSION_ENCRYPT=false
          SESSION_PATH=/
          SESSION_DOMAIN=null
          BROADCAST_CONNECTION=log
          FILESYSTEM_DISK=azure
          QUEUE_CONNECTION=database
          CACHE_STORE=database
          CACHE_PREFIX=
          MAIL_MAILER=smtp
          MAIL_HOST=
          MAIL_PORT=
          MAIL_USERNAME=
          MAIL_PASSWORD=
          MAIL_ENCRYPTION=null
          MAIL_FROM_ADDRESS="hello@minovaglobal.com"
          MAIL_FROM_NAME="${APP_NAME}"
          VITE_APP_NAME="${APP_NAME}"
          SCOUT_DRIVER=null
          STATAMIC_LICENSE_KEY=
          STATAMIC_PRO_ENABLED=true
          STATAMIC_STACHE_WATCHER=auto
          STATAMIC_STATIC_CACHING_STRATEGY=null
          STATAMIC_REVISIONS_ENABLED=false
          STATAMIC_GRAPHQL_ENABLED=false
          STATAMIC_API_ENABLED=false
          STATAMIC_GIT_ENABLED=false
          RECAPTCHA_V3_SITE_KEY=6Ldy6IUqAAAAAP2sWxPP0liS3ndTUq6LZl35GX1K
          RECAPTCHA_V3_SECRET_KEY=6Ldy6IUqAAAAAJ59_Ng2bMw_QxSIL8AlSmtuUxv_
          RECAPTCHA_V3_THRESHOLD=.5
          AZURE_STORAGE_CONNECTION_STRING=$(st-constr)
          AZURE_STORAGE_CONTAINER=$web